services:
  - type: web
    name: mgnrega-backend
    env: docker
    rootDir: backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - fromGroup: mgnrega-env
      - key: NODE_ENV
        value: production

  - type: web
    name: mgnrega-frontend
    env: docker
    rootDir: frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - fromGroup: mgnrega-env
      - key: NODE_ENV
        value: production
    dependsOn:
      - mgnrega-backend